excluded:
- Pods
- Carthage

disabled_rules:
- trailing_whitespace
- identifier_name
- discarded_notification_center_observer
- function_parameter_count
- unused_closure_parameter
- cyclomatic_complexity
- function_body_length
- unused_optional_binding
- force_cast
- block_based_kvo
- multiple_closures_with_trailing_closure
- inclusive_language

line_length:
    error: 200
    warning: 150
    ignores_comments: true

type_name:
    min_length: 2
    max_length: 80

nesting:
  type_level:
    warning: 3
    error: 6
